package com.jdahms.semantic_search.constant;

public final class VectorConstants {

    private VectorConstants() {
        // Prevent instantiation
    }

    /**
     * Dimension of the embedding vector generated by the nomic-embed-text model.
     */
    public static final int EMBEDDING_DIMENSION = 768;

    /**
     * Maximum number of rows allowed in a single CSV upload to prevent resource exhaustion.
     */
    public static final int MAX_CSV_ROWS = 1000;

    /**
     * Batch size for processing CSV uploads - commit every N rows.
     */
    public static final int CSV_BATCH_SIZE = 100;

    /**
     * Delay in milliseconds between Ollama API batch calls to prevent overwhelming the service.
     */
    public static final long OLLAMA_BATCH_DELAY_MS = 100;
}
